### ISSUE TITLE
Update readme to support custom bases

### ISSUE THREAD

**Issue by dkleissa** [gigantum/base-images#35]
We recently added keys to the `environment` section of the config file. The readme should be updated to reflect this so future users don't run into issues.

New structure:

```
environment:
  repo_url:
    - "https://github.com/gigantum/base-images.git"
  iframe:
    enabled: false
    allowed_origin: localhost:10000
```
